EntityViewCardsMaper:
  - card: LA_card
    slug: "libraryaliquot" #this should match the one from the config-knowledgebases.yaml
    filename: "LA_card.yaml"

  - card: barcodedcellsample_card
    slug: "barcodedcellsample" #this should match the one from the config-knowledgebases.yaml
    filename: "barcodedcellsample_card.yaml"

  - card: resource_card
    slug: "resource" #this should match the one from the config-knowledgebases.yaml
    filename: "resource.yaml"

  - card: CellTaxon_card
    slug: "celltaxon" # for now it is only used in hmba-taxonomy/pages.tsx
    filename: "celltaxon_card.yaml"